### ISSUE TITLE
What is the main repository for OSR 2020 website?

### ISSUE THREAD

**Issue by cmaumet** [ohbm/osr2020#8]
Hey @jsheunis and @cassgvp! 

I just fixed a typo directly on `master` and realized afterwards that the current repo (ohbm/osr2020) is a fork of (jsheunis/jsheunis.github.io) so maybe I should have pushed the change over there. Sorry for the troubles I might have created!

Can you clarify which one is the main repo (which is used to serve the website at https://ohbm.github.io/osr2020/)? 

To ease future contributions, we can outline the main repository by detaching the fork. This will retain history but make the ohbm/osr2020 (if that's the main repo) appear as non-forked. We'll have to do a request for support to do that I think. I'm happy to do this if you'd like. 

I hope that makes sense, let me know if not :D

**Comment by jsheunis** [comment]
Hey @cmaumet. This is indeed the main repo. If you have time to sort out the fork detachment, that would be great, thanks!

**Comment by cassgvp** [comment]
Thanks for fixing they typo! I’ll have someone look over all the content 👍

C

**Comment by cmaumet** [comment]
Thanks @jsheunis, I've just emailed GitHub support to ask for the fork to be detached.
