### ISSUE TITLE
Past, Present and Future of Open Science (Emergent session): Introducing Project Free Our Knowledge, the collective action platform for researchers

### ISSUE THREAD

**Issue by jsheunis** [ohbm/osr2020#85]
# Introducing Project Free Our Knowledge, the collective action platform for researchers
***By Cooper Smout, Institute for Globally Distributed Open Research and Education***

- Theme: Past, Present and Future of Open Science
- Format: Emergent session

## Abstract
Academia functions like a ‘tragedy of the commons’ dilemma: Open Science practices have the potential to benefit the collective research community (and beyond), but their adoption is limited by incentive structures that reward sloppy science and high-impact publications at the individual level. ‘Crowd-acting’ platforms (e.g., Kickstarter, Collaction) overcome such conflicting incentives by organising a critical mass of support for the intended action, prior to its adoption. Similarly, Free Our Knowledge is a new collective action problem for the research community. Researchers can pledge to support a new behaviour, but only act on that pledge if and when there is a sufficient level of community support to protect their interests. Free Our Knowledge launched last year with a number of open access campaigns, but is designed to accommodate any number of behavioural change campaigns created by the researcher community (e.g., publish open access, post data to a repository). In this session, I'll introduce the project, talk about where I think it's going, and answer any questions that may arise from the crowd.

## Useful Links
[https://www.freeourknowledge.org/](https://www.freeourknowledge.org/)
[https://github.com/freeourknowledge](https://github.com/freeourknowledge)

Tagging @CooperSmout

**Comment by CooperSmout** [comment]
Please delete this... I resubmitted with a more neuro based abstract
